DROP TABLE OCE_C2G_SCHEMA.SAMPLE_TICKET;
CREATE TABLE OCE_C2G_SCHEMA.SAMPLE_TICKET (
    TICKET_ID_NBR                  NUMBER NOT NULL,
    TICKET_TITLE_TXT               VARCHAR2(200) NOT NULL,
    TICKET_DETAIL_DESC             VARCHAR2(2000),
    TICKET_PROPS_JSON              VARCHAR2(4000),
    TICKET_STATUS_CD               VARCHAR2(20),
    VERSION_NBR                    NUMBER,
    CREATED_BY_ID                  VARCHAR2(20),
	CREATED_EPOCH_NBR              NUMBER,
    UPDATED_BY_ID                  VARCHAR2(20),
	UPDATED_EPOCH_NBR              NUMBER,
    CONSTRAINT PK_TICKET PRIMARY KEY (TICKET_ID_NBR)
);

CREATE SEQUENCE OCE_C2G_SCHEMA.SEQ_TICKET_ID MINVALUE 10001 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10001;

GRANT SELECT,UPDATE,INSERT,DELETE ON OCE_C2G_SCHEMA.SAMPLE_TICKET TO OCE_C2G_APP;

GRANT SELECT,ALTER ON OCE_C2G_SCHEMA.SEQ_TICKET_ID TO OCE_C2G_APP;

CREATE SYNONYM OCE_C2G_APP.SAMPLE_TICKET FOR OCE_C2G_SCHEMA.SAMPLE_TICKET;
CREATE SYNONYM OCE_C2G_APP.SEQ_TICKET_ID FOR OCE_C2G_SCHEMA.SEQ_TICKET_ID;

DROP TABLE OCE_C2G_SCHEMA.ENTITY_AUDIT;
CREATE TABLE OCE_C2G_SCHEMA.ENTITY_AUDIT (
    ENTITY_AUDIT_ID_NBR            NUMBER NOT NULL,
    ENTITY_ID_NBR                  NUMBER NOT NULL,
    ENTITY_TYPE_CD                 VARCHAR2(100),
    VERSION_NBR                    NUMBER,
    CREATED_BY_ID                  VARCHAR2(20),
	CREATED_EPOCH_NBR              NUMBER,
    UPDATED_BY_ID                  VARCHAR2(20),
	UPDATED_EPOCH_NBR              NUMBER,
    ENTITY_JSON                    CLOB,
    CONSTRAINT PK_ENTITY_AUDIT PRIMARY KEY (ENTITY_AUDIT_ID_NBR)
);

CREATE SEQUENCE OCE_C2G_SCHEMA.SEQ_ENTITY_AUDIT MINVALUE 10001 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10001;

GRANT SELECT,UPDATE,INSERT,DELETE ON OCE_C2G_SCHEMA.ENTITY_AUDIT TO OCE_C2G_APP;

GRANT SELECT,ALTER ON OCE_C2G_SCHEMA.SEQ_ENTITY_AUDIT TO OCE_C2G_APP;

CREATE SYNONYM OCE_C2G_APP.ENTITY_AUDIT FOR OCE_C2G_SCHEMA.ENTITY_AUDIT;
CREATE SYNONYM OCE_C2G_APP.SEQ_ENTITY_AUDIT FOR OCE_C2G_SCHEMA.SEQ_ENTITY_AUDIT;