version: '3.8'

services:
  mongodb:
    container_name: chat-mongodb
    image: bitnami/mongodb:7.0.7
#    restart: always
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/data/db'
#    command: mongod --noauth

volumes:
  mongodb_data:
    driver: local