import { Providers } from "@/app/Providers"
import SessionGuard from "./components/SessionGuard"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
            <SessionGuard>
              {children}
            </SessionGuard>
        </Providers>
      </body>
    </html>
  )
}
